services:
  ianseo:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ianseo_data:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ianseo
      MYSQL_USER: ianseo
      MYSQL_PASSWORD: ianseo
    volumes:
      - db_data:/var/lib/mysql

volumes:
  ianseo_data:
  db_data:
